spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: postgres
    password: 50cent..
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect




  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    encoding: UTF-8
    table: flyway_schema_history
    out-of-order: false
    clean-disabled: true


